import streamlit as st
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import os

# --- PAGE CONFIGURATION ---
st.set_page_config(
    page_title="DRC Ebola Live Surveillance Tracker",
    page_icon="🦠",
    layout="wide",
    initial_sidebar_state="expanded"
)

# --- DATA LOADING FUNCTION ---
@st.cache_data(ttl=3600)
def load_data():
    # Load processed dataset generated by pipeline.py
    excel_path = "DRC_Ebola_Epidemiology_Dashboard_and_Analysis.xlsx"
    if os.path.exists(excel_path):
        df = pd.read_excel(excel_path, sheet_name="Processed Data")
    else:
        st.error("Processed data file not found. Please run the ETL pipeline first.")
        st.stop()
        
    df['reference_date'] = pd.to_datetime(df['reference_date'])
    return df

df = load_data()

# --- SIDEBAR FILTERS ---
st.sidebar.title("🦠 Navigation & Filters")
st.sidebar.markdown("---")

latest_date = df['reference_date'].max()
st.sidebar.success(f"**Data Cutoff Date:** {latest_date.strftime('%Y-%m-%d')}")

# Filter by Location
all_locations = sorted(df['location_name'].dropna().unique())
selected_locations = st.sidebar.multiselect(
    "Filter by Health Zone / Location:",
    options=all_locations,
    default=all_locations[:5] if len(all_locations) >= 5 else all_locations
)

if not selected_locations:
    selected_locations = all_locations

filtered_df = df[df['location_name'].isin(selected_locations)]

# --- MAIN DASHBOARD HEADER ---
st.title("📡 DRC Ebola Epidemiological Live Surveillance")
st.markdown(
    "Automated decision-support dashboard monitoring active outbreak progression, "
    "transmission velocity, and spatial dynamics in the Democratic Republic of the Congo."
)
st.markdown("---")

# --- TOP KPI METRICS CARDS ---
confirmed_cases_df = df[(df['measure'] == 'cases') & (df['case_classification'] == 'confirmed')]
confirmed_deaths_df = df[(df['measure'] == 'deaths') & (df['case_classification'] == 'confirmed')]

daily_cases = confirmed_cases_df.groupby('reference_date')['value'].sum()
daily_deaths = confirmed_deaths_df.groupby('reference_date')['value'].sum()

latest_cases = int(daily_cases.loc[latest_date])
latest_deaths = int(daily_deaths.loc[latest_date])
latest_cfr = (latest_deaths / latest_cases * 100) if latest_cases > 0 else 0.0

# 7-Day Velocity Calculation
seven_days_ago = latest_date - pd.Timedelta(days=7)
cases_7d_ago = daily_cases.loc[seven_days_ago] if seven_days_ago in daily_cases.index else daily_cases.iloc[-8]
velocity_7d = (latest_cases - cases_7d_ago) / 7.0

col1, col2, col3, col4 = st.columns(4)

with col1:
    st.metric("Confirmed Cases", f"{latest_cases:,}", f"+{latest_cases - int(cases_7d_ago)} (7-day growth)")

with col2:
    st.metric("Confirmed Deaths", f"{latest_deaths:,}")

with col3:
    st.metric("Case Fatality Rate (CFR)", f"{latest_cfr:.1f}%")

with col4:
    st.metric("7-Day Velocity", f"{velocity_7d:.1f} cases/day")

st.markdown("---")

# --- CHARTS SECTION ---
tab1, tab2, tab3 = st.tabs(["📈 Epidemic Trajectory", "📍 Health Zone Analysis", "🔍 Data Quality Audit"])

with tab1:
    st.subheader("Cumulative Growth & 7-Day Transmission Velocity")
    
    # Time series plot
    ts_agg = confirmed_cases_df.groupby('reference_date')['value'].sum().reset_index()
    
    fig_ts = px.line(
        ts_agg, 
        x='reference_date', 
        y='value', 
        title="Cumulative Confirmed Cases Over Time",
        labels={'reference_date': 'Date', 'value': 'Confirmed Cases'},
        line_shape='spline'
    )
    fig_ts.update_traces(line_color="#E63946", line_width=3)
    fig_ts.update_layout(template="plotly_white", hovermode="x unified")
    st.plotly_chart(fig_ts, use_container_width=True)

with tab2:
    st.subheader("Location Burden Breakdown")
    loc_agg = filtered_df[
        (filtered_df['measure'] == 'cases') & 
        (filtered_df['case_classification'] == 'confirmed') & 
        (filtered_df['reference_date'] == latest_date)
    ].groupby('location_name')['value'].sum().reset_index().sort_values(by='value', ascending=False)
    
    fig_bar = px.bar(
        loc_agg,
        x='value',
        y='location_name',
        orientation='h',
        title=f"Confirmed Cases by Location (As of {latest_date.strftime('%Y-%m-%d')})",
        labels={'value': 'Cases', 'location_name': 'Health Zone'},
        color='value',
        color_continuous_scale='Reds'
    )
    fig_bar.update_layout(template="plotly_white", yaxis={'categoryorder': 'total ascending'})
    st.plotly_chart(fig_bar, use_container_width=True)

with tab3:
    st.subheader("Automated Data Quality Audit Summary")
    dq_counts = df['dq_status'].value_counts().reset_index()
    dq_counts.columns = ['DQ Status', 'Record Count']
    
    fig_pie = px.pie(
        dq_counts, 
        names='DQ Status', 
        values='Record Count',
        title="Distribution of Automated Data Quality Audit Flags",
        color_discrete_sequence=px.colors.qualitative.Set2
    )
    st.plotly_chart(fig_pie, use_container_width=True)
    
    st.dataframe(df[df['dq_status'] != 'Normal'][['reference_date', 'location_name', 'measure', 'value', 'dq_status']].tail(10), use_container_width=True)

# --- FOOTER ---
st.markdown("---")
st.caption("🤖 Data Pipeline Engine: Python / Pandas / HDX API | Deployed via Streamlit & GitHub Actions")

st.caption("📝 Data Source: https://hdx.rdc.go.ug/dataset/republique-democratique-du-congo-cas-et-deces-d-ebola")